Feature to exclude an asset via command line parameter #260
istio-ecosystem/admiral pull request #261
Opened 2022-09-19 22:26 UTC by nirvanagit

2022-09-26 17:17 UTC, shriramsharma approved these changes

2022-09-28 17:52 UTC, aattuluri requested changes

2022-09-28 17:52 UTC, aattuluri commented on admiral/pkg/clusters/types.go
> +func isAnExcludedAsset(assetName string, excludedAssetList []string) bool {
Can you convert `excludedAssetList` into a map?
```suggestion
func isAnExcludedAsset(assetName string, excludedIdentityList []string) bool {
```

2022-10-01 00:37 UTC, aattuluri approved these changes
Lgtm

2022-10-03 16:59 UTC, merged